name: Deploy to Development

on:
  push:
    branches:
      - main
      - master
env:
  ENV: development
  AWS_ACCESS_KEY_ID: ${{ secrets.DEVELOPMENT_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEVELOPMENT_AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ vars.DEVELOPMENT_AWS_ACCOUNT_ID }}
  AWS_ECR_REGION: ${{ vars.DEVELOPMENT_AWS_ECR_REGION }}
  AWS_ECR_REPO_NAME: ${{ vars.DEVELOPMENT_AWS_ECR_REPO_NAME }}
  AWS_JH_ENV_SECRET_NAME: ${{ vars.DEVELOPMENT_AWS_JH_ENV_SECRET_NAME }}
  AWS_ENV_USER_ACCESS_KEY_ID: ${{ secrets.DEVELOPMENT_AWS_ENV_USER_ACCESS_KEY_ID }}
  AWS_ENV_USER_SECRET_ACCESS_KEY: ${{ secrets.DEVELOPMENT_AWS_ENV_USER_SECRET_ACCESS_KEY }}
  AWS_ENV_USER_REGION: ${{ vars.DEVELOPMENT_AWS_ENV_USER_REGION }}
  AWS_ECR_TAG_NAME: ${{ vars.DEVELOPMENT_AWS_ECR_TAG_NAME }}
  AWS_PROFILE_PARAM: ${{ vars.DEVELOPMENT_AWS_PROFILE_PARAM }}
  ENV_FILE_PATH: ${{ vars.DEVELOPMENT_ENV_FILE_PATH }}
  AWS_INSTANCE_DEPLOY_SCRIPT: ${{ vars.DEVELOPMENT_AWS_INSTANCE_DEPLOY_SCRIPT }}
  AWS_INSTANCE_URL: ${{ secrets.DEVELOPMENT_AWS_INSTANCE_URL }}
  USE_SSH_DEPLOYMENT: ${{ vars.DEVELOPMENT_USE_SSH_DEPLOYMENT }}
  ENCODED_PEM: ${{ secrets.DEVELOPMENT_ENCODED_PEM }}

jobs:
  deploy:
    runs-on: [self-hosted]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Run deploy script to build docker and ship docker to ECR
        run: ./scripts/deploy.sh
